### ISSUE TITLE
불필요한 자바스크립트 로그 삭제

### ISSUE THREAD

**Issue by mikonu** [djkeh/test-data#63]
https://github.com/djkeh/test-data/blob/743a0028d4ceb81d985a2cfc63e05bcb3a3387ab/src/main/resources/templates/table-schema.html#L136

위 라인의 `console.log()`는 자바스크립트 로깅 코드인데, 주로 개발에만 관찰용으로 사용하는 코드이다.
이 부분은 불필요한 코드이므로 삭제하는 것이 좋다.

@djkeh 수업 중에 많이 피곤하셨나봐요?

**Comment by djkeh** [comment]
![Image](https://github.com/user-attachments/assets/cb7cad7e-cf75-4e04-8b49-b6c5dd667dd0)

진행시켜.

**Comment by mikonu** [comment]
그렇다고 한다.
